server:
  port: 8001

# MyBatis
mybatis:
  configLocation: classpath:mybatis/mybatis.cfg.xml
  typeAliasesPackage: cn.shiyu.entity
  mapperLocations: mybatis/mapper/**/*.xml
    
spring:
    application:
        name: happyshiyu-Blog-User
    datasource:
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shiyu_blog
        username: root
        password: 123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: blog-user-8001
    prefer-ip-address: true #访问路径可以显示ip地址
   